apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventhubsoutput
spec:
  type: bindings.kafka
  metadata:
    - name: brokers
      value: vscodebook.servicebus.windows.net:9093
    - name: publishTopic
      value: jobrequesttopic
    - name: consumerGroup
      value: $Default
    - name: authRequired
      value: true
    - name: saslUsername
      value: $ConnectionString
    - name: saslPassword
      value: Endpoint=sb://vscodebook.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=7f2bWIsiOXuvV4ZkWkr/IuBZk4/0C5roqUWeZpTQlwM=;EntityPath=jobrequesttopic